[build-system]
requires = ["setuptools>=64"]
build-backend = "setuptools.build_meta"

[project]
name = "fabricpy"
version = "0.1.0"
description = "Read Microsoft Fabric Lakehouse tables via OneLake HTTPS API"
authors = [
    { name = "Derick Imbati", email = "derick.imbati@aku.edu" },
]
license = { text = "Apache-2.0" }
requires-python = ">=3.10"
dependencies = []

[project.optional-dependencies]
pandas = ["deltalake", "pandas>=1.5,<3"]
sql = ["deltalake", "duckdb", "pandas>=1.5,<3"]
sqlserver = ["pandas>=1.5,<3", "pyodbc", "azure-identity", "azure-keyvault-secrets"]

[tool.setuptools.package-data]
fabricpy = ["config.json"]


